// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers, omit_obvious_local_variable_types
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:gazer/pigeon/pipeline.g.dart';

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is VideoDeviceKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is AudioDeviceKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NativePipelineState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is GazerErrorCode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is OutputOrientation) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is VideoDevice) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is AudioDevice) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is StreamConfig) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is StreamTarget) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PrepareResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is StatsSample) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is StateEvent) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VideoDeviceKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AudioDeviceKind.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativePipelineState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : GazerErrorCode.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : OutputOrientation.values[value];
      case 134:
        return VideoDevice.decode(readValue(buffer)!);
      case 135:
        return AudioDevice.decode(readValue(buffer)!);
      case 136:
        return StreamConfig.decode(readValue(buffer)!);
      case 137:
        return StreamTarget.decode(readValue(buffer)!);
      case 138:
        return PrepareResult.decode(readValue(buffer)!);
      case 139:
        return StatsSample.decode(readValue(buffer)!);
      case 140:
        return StateEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
