---
version: "2.4"
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
  waddlebot-listener:
    build: .
    env_file: .env
    restart: always
    depends_on:
      redis:
        condition: service_started

volumes:
  redis_volume_data:
  redis_insight_volume_data: