// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Kind of video source a device entry represents.
enum VideoDeviceKind { backCamera, frontCamera, uvcCamera2, uvcLibuvc }

/// Kind of audio source a device entry represents.
enum AudioDeviceKind { mic, usbAudio, silence }

/// Native pipeline state machine, as reported by the Kotlin side. Dart adds
/// the `reconnecting` state on top of this (see the Dart `PipelineState`).
enum NativePipelineState {
  idle,
  preparing,
  ready,
  connecting,
  streaming,
  stopping,
  error,
}

/// Error classification for every failure the native pipeline can report.
enum GazerErrorCode {
  usbPermissionDenied,
  uvcNoUsableFormat,
  uvcOpenFailed,
  cameraUnavailable,
  cameraInUse,
  encoderFailed,
  audioSourceFailed,
  rtmpAuthFailed,
  rtmpConnectFailed,
  rtmpDisconnected,
  usbDetached,
  serviceStartDenied,
  unknown,
}

/// Requested output orientation for the encoded video (camera path only;
/// UVC is always landscape).
enum OutputOrientation { landscape, portrait }

/// One enumerable video source (a camera or an attached UVC device).
class VideoDevice {
  VideoDevice({
    required this.id,
    required this.kind,
    required this.name,
    this.vendorId,
    this.productId,
  });

  String id;

  VideoDeviceKind kind;

  String name;

  int? vendorId;

  int? productId;

  List<Object?> _toList() {
    return <Object?>[id, kind, name, vendorId, productId];
  }

  Object encode() {
    return _toList();
  }

  static VideoDevice decode(Object result) {
    result as List<Object?>;
    return VideoDevice(
      id: result[0]! as String,
      kind: result[1]! as VideoDeviceKind,
      name: result[2]! as String,
      vendorId: result[3] as int?,
      productId: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(name, other.name) &&
        _deepEquals(vendorId, other.vendorId) &&
        _deepEquals(productId, other.productId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoDevice(id: $id, kind: $kind, name: $name, vendorId: $vendorId, productId: $productId)';
  }
}

/// One enumerable audio source.
class AudioDevice {
  AudioDevice({required this.id, required this.kind, required this.name});

  String id;

  AudioDeviceKind kind;

  String name;

  List<Object?> _toList() {
    return <Object?>[id, kind, name];
  }

  Object encode() {
    return _toList();
  }

  static AudioDevice decode(Object result) {
    result as List<Object?>;
    return AudioDevice(
      id: result[0]! as String,
      kind: result[1]! as AudioDeviceKind,
      name: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(name, other.name);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioDevice(id: $id, kind: $kind, name: $name)';
  }
}

/// Parameters for `GazerHostApi.prepare` describing the encoder/source setup.
class StreamConfig {
  StreamConfig({
    required this.videoDeviceId,
    required this.audioDeviceId,
    required this.width,
    required this.height,
    required this.fps,
    required this.videoBitrateKbps,
    required this.adaptiveBitrate,
    required this.audioBitrateKbps,
    required this.orientation,
  });

  String videoDeviceId;

  String audioDeviceId;

  int width;

  int height;

  int fps;

  int videoBitrateKbps;

  bool adaptiveBitrate;

  int audioBitrateKbps;

  OutputOrientation orientation;

  List<Object?> _toList() {
    return <Object?>[
      videoDeviceId,
      audioDeviceId,
      width,
      height,
      fps,
      videoBitrateKbps,
      adaptiveBitrate,
      audioBitrateKbps,
      orientation,
    ];
  }

  Object encode() {
    return _toList();
  }

  static StreamConfig decode(Object result) {
    result as List<Object?>;
    return StreamConfig(
      videoDeviceId: result[0]! as String,
      audioDeviceId: result[1]! as String,
      width: result[2]! as int,
      height: result[3]! as int,
      fps: result[4]! as int,
      videoBitrateKbps: result[5]! as int,
      adaptiveBitrate: result[6]! as bool,
      audioBitrateKbps: result[7]! as int,
      orientation: result[8]! as OutputOrientation,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StreamConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(videoDeviceId, other.videoDeviceId) &&
        _deepEquals(audioDeviceId, other.audioDeviceId) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(fps, other.fps) &&
        _deepEquals(videoBitrateKbps, other.videoBitrateKbps) &&
        _deepEquals(adaptiveBitrate, other.adaptiveBitrate) &&
        _deepEquals(audioBitrateKbps, other.audioBitrateKbps) &&
        _deepEquals(orientation, other.orientation);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StreamConfig(videoDeviceId: $videoDeviceId, audioDeviceId: $audioDeviceId, width: $width, height: $height, fps: $fps, videoBitrateKbps: $videoBitrateKbps, adaptiveBitrate: $adaptiveBitrate, audioBitrateKbps: $audioBitrateKbps, orientation: $orientation)';
  }
}

/// RTMP/RTMPS destination passed to `GazerHostApi.start`. `url` already has
/// the stream key folded in by `TargetValidator.effectiveUrl` on the Dart
/// side — Kotlin never appends a key itself.
class StreamTarget {
  StreamTarget({required this.url, this.username, this.password});

  String url;

  String? username;

  String? password;

  List<Object?> _toList() {
    return <Object?>[url, username, password];
  }

  Object encode() {
    return _toList();
  }

  static StreamTarget decode(Object result) {
    result as List<Object?>;
    return StreamTarget(
      url: result[0]! as String,
      username: result[1] as String?,
      password: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StreamTarget || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(url, other.url) &&
        _deepEquals(username, other.username) &&
        _deepEquals(password, other.password);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StreamTarget(url: $url, username: $username, password: $password)';
  }
}

/// Result of `GazerHostApi.prepare`: whether the source/encoder negotiated
/// successfully and, if so, what was actually negotiated.
class PrepareResult {
  PrepareResult({
    required this.ok,
    this.error,
    this.detail,
    this.negotiatedWidth,
    this.negotiatedHeight,
    this.negotiatedFps,
    this.negotiatedFormat,
  });

  bool ok;

  GazerErrorCode? error;

  String? detail;

  int? negotiatedWidth;

  int? negotiatedHeight;

  int? negotiatedFps;

  String? negotiatedFormat;

  List<Object?> _toList() {
    return <Object?>[
      ok,
      error,
      detail,
      negotiatedWidth,
      negotiatedHeight,
      negotiatedFps,
      negotiatedFormat,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PrepareResult decode(Object result) {
    result as List<Object?>;
    return PrepareResult(
      ok: result[0]! as bool,
      error: result[1] as GazerErrorCode?,
      detail: result[2] as String?,
      negotiatedWidth: result[3] as int?,
      negotiatedHeight: result[4] as int?,
      negotiatedFps: result[5] as int?,
      negotiatedFormat: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrepareResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(ok, other.ok) &&
        _deepEquals(error, other.error) &&
        _deepEquals(detail, other.detail) &&
        _deepEquals(negotiatedWidth, other.negotiatedWidth) &&
        _deepEquals(negotiatedHeight, other.negotiatedHeight) &&
        _deepEquals(negotiatedFps, other.negotiatedFps) &&
        _deepEquals(negotiatedFormat, other.negotiatedFormat);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrepareResult(ok: $ok, error: $error, detail: $detail, negotiatedWidth: $negotiatedWidth, negotiatedHeight: $negotiatedHeight, negotiatedFps: $negotiatedFps, negotiatedFormat: $negotiatedFormat)';
  }
}

/// One 1Hz statistics sample emitted by the native encoder/publisher.
class StatsSample {
  StatsSample({
    required this.bitrateKbps,
    required this.fps,
    required this.droppedVideoFrames,
    required this.sentBytes,
    required this.congestionPercent,
  });

  int bitrateKbps;

  double fps;

  int droppedVideoFrames;

  int sentBytes;

  double congestionPercent;

  List<Object?> _toList() {
    return <Object?>[
      bitrateKbps,
      fps,
      droppedVideoFrames,
      sentBytes,
      congestionPercent,
    ];
  }

  Object encode() {
    return _toList();
  }

  static StatsSample decode(Object result) {
    result as List<Object?>;
    return StatsSample(
      bitrateKbps: result[0]! as int,
      fps: result[1]! as double,
      droppedVideoFrames: result[2]! as int,
      sentBytes: result[3]! as int,
      congestionPercent: result[4]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StatsSample || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(bitrateKbps, other.bitrateKbps) &&
        _deepEquals(fps, other.fps) &&
        _deepEquals(droppedVideoFrames, other.droppedVideoFrames) &&
        _deepEquals(sentBytes, other.sentBytes) &&
        _deepEquals(congestionPercent, other.congestionPercent);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StatsSample(bitrateKbps: $bitrateKbps, fps: $fps, droppedVideoFrames: $droppedVideoFrames, sentBytes: $sentBytes, congestionPercent: $congestionPercent)';
  }
}

/// A native pipeline state transition, optionally carrying an error.
class StateEvent {
  StateEvent({required this.state, this.error, this.detail});

  NativePipelineState state;

  GazerErrorCode? error;

  String? detail;

  List<Object?> _toList() {
    return <Object?>[state, error, detail];
  }

  Object encode() {
    return _toList();
  }

  static StateEvent decode(Object result) {
    result as List<Object?>;
    return StateEvent(
      state: result[0]! as NativePipelineState,
      error: result[1] as GazerErrorCode?,
      detail: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) &&
        _deepEquals(error, other.error) &&
        _deepEquals(detail, other.detail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StateEvent(state: $state, error: $error, detail: $detail)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is VideoDeviceKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is AudioDeviceKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NativePipelineState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is GazerErrorCode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is OutputOrientation) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is VideoDevice) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is AudioDevice) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is StreamConfig) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is StreamTarget) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PrepareResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is StatsSample) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is StateEvent) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VideoDeviceKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AudioDeviceKind.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativePipelineState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : GazerErrorCode.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : OutputOrientation.values[value];
      case 134:
        return VideoDevice.decode(readValue(buffer)!);
      case 135:
        return AudioDevice.decode(readValue(buffer)!);
      case 136:
        return StreamConfig.decode(readValue(buffer)!);
      case 137:
        return StreamTarget.decode(readValue(buffer)!);
      case 138:
        return PrepareResult.decode(readValue(buffer)!);
      case 139:
        return StatsSample.decode(readValue(buffer)!);
      case 140:
        return StateEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Commands Dart issues to the native pipeline (Dart -> Kotlin).
class GazerHostApi {
  /// Constructor for [GazerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  GazerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Enumerates available video sources (back/front camera; UVC devices
  /// attached at call time).
  Future<List<VideoDevice>> listVideoDevices() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.gazer.GazerHostApi.listVideoDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<VideoDevice>();
  }

  /// Enumerates available audio sources.
  Future<List<AudioDevice>> listAudioDevices() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.gazer.GazerHostApi.listAudioDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<AudioDevice>();
  }

  /// Requests OS-level USB permission for [deviceId]. M1 always returns
  /// false: no UVC devices are ever listed, so this is never actually
  /// invoked with a real device in this milestone.
  Future<bool> requestUsbPermission(String deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.gazer.GazerHostApi.requestUsbPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Negotiates the source/encoder for [config]; must succeed before `start`.
  Future<PrepareResult> prepare(StreamConfig config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.gazer.GazerHostApi.prepare$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PrepareResult;
  }

  /// Begins publishing to [target]; only valid after a successful `prepare`.
  Future<void> start(StreamTarget target) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.gazer.GazerHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[target],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Stops publishing and tears down the source/encoder.
  Future<void> stop() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.gazer.GazerHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Adjusts the live video bitrate without a full restart (used by the
  /// native `BitrateAdapter` and by Dart-driven manual overrides).
  Future<void> setVideoBitrate(int kbps) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.gazer.GazerHostApi.setVideoBitrate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[kbps],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Returns the native pipeline's current state synchronously.
  Future<NativePipelineState> getState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.gazer.GazerHostApi.getState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativePipelineState;
  }
}

/// Events the native pipeline pushes to Dart (Kotlin -> Dart).
abstract class GazerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Fired on every native state transition.
  void onStateChanged(StateEvent event);

  /// Fired at 1Hz while prepared/streaming.
  void onStats(StatsSample sample);

  /// Fired when a UVC device is physically attached (M1: never fired).
  void onUsbAttached(VideoDevice device);

  /// Fired when a UVC device is physically detached (M1: never fired).
  void onUsbDetached(String deviceId);

  /// Fired after an RTMP auth attempt resolves.
  void onAuthResult(bool ok);

  static void setUp(
    GazerFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gazer.GazerFlutterApi.onStateChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final StateEvent arg_event = args[0]! as StateEvent;
          try {
            api.onStateChanged(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gazer.GazerFlutterApi.onStats$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final StatsSample arg_sample = args[0]! as StatsSample;
          try {
            api.onStats(arg_sample);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gazer.GazerFlutterApi.onUsbAttached$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VideoDevice arg_device = args[0]! as VideoDevice;
          try {
            api.onUsbAttached(arg_device);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gazer.GazerFlutterApi.onUsbDetached$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_deviceId = args[0]! as String;
          try {
            api.onUsbDetached(arg_deviceId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.gazer.GazerFlutterApi.onAuthResult$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_ok = args[0]! as bool;
          try {
            api.onAuthResult(arg_ok);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
