"""AUTO-GENERATED by scripts/generate_bundle_preimports.py -- DO NOT EDIT BY HAND.

Forces componentize-py's static dependency-closure discovery to see every
module physically present under `bundles/`, independent of whether the
bundle code itself imports them lazily, dynamically, or not at all this run.
See that script's docstring and REPORT.md Round 2, blocker (2).
"""

from __future__ import annotations

import bundles.bot_process  # noqa: F401
import bundles.social_alias_process  # noqa: F401
