# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import translate_interaction_pb2 as translate__interaction__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in translate_interaction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslateInteractionStub(object):
    """Translation service — called by router in the hot message-processing path
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Translate = channel.unary_unary(
                '/translate_interaction.TranslateInteraction/Translate',
                request_serializer=translate__interaction__pb2.TranslateRequest.SerializeToString,
                response_deserializer=translate__interaction__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.DetectLanguage = channel.unary_unary(
                '/translate_interaction.TranslateInteraction/DetectLanguage',
                request_serializer=translate__interaction__pb2.DetectLanguageRequest.SerializeToString,
                response_deserializer=translate__interaction__pb2.DetectLanguageResponse.FromString,
                _registered_method=True)
        self.CleanupCache = channel.unary_unary(
                '/translate_interaction.TranslateInteraction/CleanupCache',
                request_serializer=translate__interaction__pb2.CleanupCacheRequest.SerializeToString,
                response_deserializer=translate__interaction__pb2.CleanupCacheResponse.FromString,
                _registered_method=True)


class TranslateInteractionServicer(object):
    """Translation service — called by router in the hot message-processing path
    """

    def Translate(self, request, context):
        """Translate a chat message (primary hot-path call)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectLanguage(self, request, context):
        """Detect language only, without translating
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupCache(self, request, context):
        """Trigger cache cleanup (admin/maintenance)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslateInteractionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=translate__interaction__pb2.TranslateRequest.FromString,
                    response_serializer=translate__interaction__pb2.TranslateResponse.SerializeToString,
            ),
            'DetectLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLanguage,
                    request_deserializer=translate__interaction__pb2.DetectLanguageRequest.FromString,
                    response_serializer=translate__interaction__pb2.DetectLanguageResponse.SerializeToString,
            ),
            'CleanupCache': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupCache,
                    request_deserializer=translate__interaction__pb2.CleanupCacheRequest.FromString,
                    response_serializer=translate__interaction__pb2.CleanupCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'translate_interaction.TranslateInteraction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('translate_interaction.TranslateInteraction', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslateInteraction(object):
    """Translation service — called by router in the hot message-processing path
    """

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translate_interaction.TranslateInteraction/Translate',
            translate__interaction__pb2.TranslateRequest.SerializeToString,
            translate__interaction__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translate_interaction.TranslateInteraction/DetectLanguage',
            translate__interaction__pb2.DetectLanguageRequest.SerializeToString,
            translate__interaction__pb2.DetectLanguageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translate_interaction.TranslateInteraction/CleanupCache',
            translate__interaction__pb2.CleanupCacheRequest.SerializeToString,
            translate__interaction__pb2.CleanupCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
