{{- if .Values.enabled }}
{{- if .Values.agent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "waddlebot-spire.agentServiceAccountName" . }}
  labels:
    {{- include "waddlebot-spire.labels" . | nindent 4 }}
    component: agent
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
