{{- if .Values.enabled }}
{{- if .Values.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "waddlebot-spire.serverServiceAccountName" . }}
  labels:
    {{- include "waddlebot-spire.labels" . | nindent 4 }}
    component: server
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
