// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.waddlebot.gazer.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

private object PipelinePigeonUtils {
    fun createConnectionError(channelName: String): FlutterError =
        FlutterError("channel-error", "Unable to establish connection on channel: '$channelName'.", "")

    fun wrapResult(result: Any?): List<Any?> = listOf(result)

    fun wrapError(exception: Throwable): List<Any?> =
        if (exception is FlutterError) {
            listOf(
                exception.code,
                exception.message,
                exception.details,
            )
        } else {
            listOf(
                exception.javaClass.simpleName,
                exception.toString(),
                "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
            )
        }

    fun doubleEquals(
        a: Double,
        b: Double,
    ): Boolean {
        // Normalize -0.0 to 0.0 and handle NaN equality.
        return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
    }

    fun floatEquals(
        a: Float,
        b: Float,
    ): Boolean {
        // Normalize -0.0 to 0.0 and handle NaN equality.
        return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
    }

    fun doubleHash(d: Double): Int {
        // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
        val normalized = if (d == 0.0) 0.0 else d
        val bits = java.lang.Double.doubleToLongBits(normalized)
        return (bits xor (bits ushr 32)).toInt()
    }

    fun floatHash(f: Float): Int {
        // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
        val normalized = if (f == 0.0f) 0.0f else f
        return java.lang.Float.floatToIntBits(normalized)
    }

    fun deepEquals(
        a: Any?,
        b: Any?,
    ): Boolean {
        if (a === b) {
            return true
        }
        if (a == null || b == null) {
            return false
        }
        if (a is ByteArray && b is ByteArray) {
            return a.contentEquals(b)
        }
        if (a is IntArray && b is IntArray) {
            return a.contentEquals(b)
        }
        if (a is LongArray && b is LongArray) {
            return a.contentEquals(b)
        }
        if (a is DoubleArray && b is DoubleArray) {
            if (a.size != b.size) return false
            for (i in a.indices) {
                if (!doubleEquals(a[i], b[i])) return false
            }
            return true
        }
        if (a is FloatArray && b is FloatArray) {
            if (a.size != b.size) return false
            for (i in a.indices) {
                if (!floatEquals(a[i], b[i])) return false
            }
            return true
        }
        if (a is Array<*> && b is Array<*>) {
            if (a.size != b.size) return false
            for (i in a.indices) {
                if (!deepEquals(a[i], b[i])) return false
            }
            return true
        }
        if (a is List<*> && b is List<*>) {
            if (a.size != b.size) return false
            val iterA = a.iterator()
            val iterB = b.iterator()
            while (iterA.hasNext() && iterB.hasNext()) {
                if (!deepEquals(iterA.next(), iterB.next())) return false
            }
            return true
        }
        if (a is Map<*, *> && b is Map<*, *>) {
            if (a.size != b.size) return false
            for (entry in a) {
                val key = entry.key
                var found = false
                for (bEntry in b) {
                    if (deepEquals(key, bEntry.key)) {
                        if (deepEquals(entry.value, bEntry.value)) {
                            found = true
                            break
                        } else {
                            return false
                        }
                    }
                }
                if (!found) return false
            }
            return true
        }
        if (a is Double && b is Double) {
            return doubleEquals(a, b)
        }
        if (a is Float && b is Float) {
            return floatEquals(a, b)
        }
        return a == b
    }

    fun deepHash(value: Any?): Int =
        when (value) {
            null -> 0
            is ByteArray -> value.contentHashCode()
            is IntArray -> value.contentHashCode()
            is LongArray -> value.contentHashCode()
            is DoubleArray -> {
                var result = 1
                for (item in value) {
                    result = 31 * result + doubleHash(item)
                }
                result
            }
            is FloatArray -> {
                var result = 1
                for (item in value) {
                    result = 31 * result + floatHash(item)
                }
                result
            }
            is Array<*> -> {
                var result = 1
                for (item in value) {
                    result = 31 * result + deepHash(item)
                }
                result
            }
            is List<*> -> {
                var result = 1
                for (item in value) {
                    result = 31 * result + deepHash(item)
                }
                result
            }
            is Map<*, *> -> {
                var result = 0
                for (entry in value) {
                    result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
                }
                result
            }
            is Double -> doubleHash(value)
            is Float -> floatHash(value)
            else -> value.hashCode()
        }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
    val code: String,
    override val message: String? = null,
    val details: Any? = null,
) : RuntimeException()

/** Kind of video source a device entry represents. */
enum class VideoDeviceKind(
    val raw: Int,
) {
    BACK_CAMERA(0),
    FRONT_CAMERA(1),
    UVC_CAMERA2(2),
    UVC_LIBUVC(3),
    ;

    companion object {
        fun ofRaw(raw: Int): VideoDeviceKind? = values().firstOrNull { it.raw == raw }
    }
}

/** Kind of audio source a device entry represents. */
enum class AudioDeviceKind(
    val raw: Int,
) {
    MIC(0),
    USB_AUDIO(1),
    SILENCE(2),
    ;

    companion object {
        fun ofRaw(raw: Int): AudioDeviceKind? = values().firstOrNull { it.raw == raw }
    }
}

/**
 * Native pipeline state machine, as reported by the Kotlin side. Dart adds
 * the `reconnecting` state on top of this (see the Dart `PipelineState`).
 */
enum class NativePipelineState(
    val raw: Int,
) {
    IDLE(0),
    PREPARING(1),
    READY(2),
    CONNECTING(3),
    STREAMING(4),
    STOPPING(5),
    ERROR(6),
    ;

    companion object {
        fun ofRaw(raw: Int): NativePipelineState? = values().firstOrNull { it.raw == raw }
    }
}

/** Error classification for every failure the native pipeline can report. */
enum class GazerErrorCode(
    val raw: Int,
) {
    USB_PERMISSION_DENIED(0),
    UVC_NO_USABLE_FORMAT(1),
    UVC_OPEN_FAILED(2),
    CAMERA_UNAVAILABLE(3),
    CAMERA_IN_USE(4),
    ENCODER_FAILED(5),
    AUDIO_SOURCE_FAILED(6),
    RTMP_AUTH_FAILED(7),
    RTMP_CONNECT_FAILED(8),
    RTMP_DISCONNECTED(9),
    USB_DETACHED(10),
    SERVICE_START_DENIED(11),
    UNKNOWN(12),
    ;

    companion object {
        fun ofRaw(raw: Int): GazerErrorCode? = values().firstOrNull { it.raw == raw }
    }
}

/**
 * Requested output orientation for the encoded video (camera path only;
 * UVC is always landscape).
 */
enum class OutputOrientation(
    val raw: Int,
) {
    LANDSCAPE(0),
    PORTRAIT(1),
    ;

    companion object {
        fun ofRaw(raw: Int): OutputOrientation? = values().firstOrNull { it.raw == raw }
    }
}

/**
 * One enumerable video source (a camera or an attached UVC device).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoDevice(
    val id: String,
    val kind: VideoDeviceKind,
    val name: String,
    val vendorId: Long? = null,
    val productId: Long? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): VideoDevice {
            val id = pigeonVar_list[0] as String
            val kind = pigeonVar_list[1] as VideoDeviceKind
            val name = pigeonVar_list[2] as String
            val vendorId = pigeonVar_list[3] as Long?
            val productId = pigeonVar_list[4] as Long?
            return VideoDevice(id, kind, name, vendorId, productId)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            id,
            kind,
            name,
            vendorId,
            productId,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as VideoDevice
        return PipelinePigeonUtils.deepEquals(this.id, other.id) &&
            PipelinePigeonUtils.deepEquals(this.kind, other.kind) &&
            PipelinePigeonUtils.deepEquals(this.name, other.name) &&
            PipelinePigeonUtils.deepEquals(this.vendorId, other.vendorId) &&
            PipelinePigeonUtils.deepEquals(this.productId, other.productId)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + PipelinePigeonUtils.deepHash(this.id)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.kind)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.name)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.vendorId)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.productId)
        return result
    }

    override fun toString(): String = "VideoDevice(id=$id, kind=$kind, name=$name, vendorId=$vendorId, productId=$productId)"
}

/**
 * One enumerable audio source.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AudioDevice(
    val id: String,
    val kind: AudioDeviceKind,
    val name: String,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): AudioDevice {
            val id = pigeonVar_list[0] as String
            val kind = pigeonVar_list[1] as AudioDeviceKind
            val name = pigeonVar_list[2] as String
            return AudioDevice(id, kind, name)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            id,
            kind,
            name,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as AudioDevice
        return PipelinePigeonUtils.deepEquals(this.id, other.id) &&
            PipelinePigeonUtils.deepEquals(this.kind, other.kind) &&
            PipelinePigeonUtils.deepEquals(this.name, other.name)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + PipelinePigeonUtils.deepHash(this.id)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.kind)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.name)
        return result
    }

    override fun toString(): String = "AudioDevice(id=$id, kind=$kind, name=$name)"
}

/**
 * Parameters for `GazerHostApi.prepare` describing the encoder/source setup.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StreamConfig(
    val videoDeviceId: String,
    val audioDeviceId: String,
    val width: Long,
    val height: Long,
    val fps: Long,
    val videoBitrateKbps: Long,
    val adaptiveBitrate: Boolean,
    val audioBitrateKbps: Long,
    val orientation: OutputOrientation,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): StreamConfig {
            val videoDeviceId = pigeonVar_list[0] as String
            val audioDeviceId = pigeonVar_list[1] as String
            val width = pigeonVar_list[2] as Long
            val height = pigeonVar_list[3] as Long
            val fps = pigeonVar_list[4] as Long
            val videoBitrateKbps = pigeonVar_list[5] as Long
            val adaptiveBitrate = pigeonVar_list[6] as Boolean
            val audioBitrateKbps = pigeonVar_list[7] as Long
            val orientation = pigeonVar_list[8] as OutputOrientation
            return StreamConfig(
                videoDeviceId,
                audioDeviceId,
                width,
                height,
                fps,
                videoBitrateKbps,
                adaptiveBitrate,
                audioBitrateKbps,
                orientation,
            )
        }
    }

    fun toList(): List<Any?> =
        listOf(
            videoDeviceId,
            audioDeviceId,
            width,
            height,
            fps,
            videoBitrateKbps,
            adaptiveBitrate,
            audioBitrateKbps,
            orientation,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as StreamConfig
        return PipelinePigeonUtils.deepEquals(this.videoDeviceId, other.videoDeviceId) &&
            PipelinePigeonUtils.deepEquals(this.audioDeviceId, other.audioDeviceId) &&
            PipelinePigeonUtils.deepEquals(this.width, other.width) &&
            PipelinePigeonUtils.deepEquals(this.height, other.height) &&
            PipelinePigeonUtils.deepEquals(this.fps, other.fps) &&
            PipelinePigeonUtils.deepEquals(this.videoBitrateKbps, other.videoBitrateKbps) &&
            PipelinePigeonUtils.deepEquals(this.adaptiveBitrate, other.adaptiveBitrate) &&
            PipelinePigeonUtils.deepEquals(this.audioBitrateKbps, other.audioBitrateKbps) &&
            PipelinePigeonUtils.deepEquals(this.orientation, other.orientation)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + PipelinePigeonUtils.deepHash(this.videoDeviceId)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.audioDeviceId)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.width)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.height)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.fps)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.videoBitrateKbps)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.adaptiveBitrate)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.audioBitrateKbps)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.orientation)
        return result
    }

    override fun toString(): String =
        "StreamConfig(videoDeviceId=$videoDeviceId, audioDeviceId=$audioDeviceId, " +
            "width=$width, height=$height, fps=$fps, videoBitrateKbps=$videoBitrateKbps, " +
            "adaptiveBitrate=$adaptiveBitrate, audioBitrateKbps=$audioBitrateKbps, orientation=$orientation)"
}

/**
 * RTMP/RTMPS destination passed to `GazerHostApi.start`. `url` already has
 * the stream key folded in by `TargetValidator.effectiveUrl` on the Dart
 * side — Kotlin never appends a key itself.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StreamTarget(
    val url: String,
    val username: String? = null,
    val password: String? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): StreamTarget {
            val url = pigeonVar_list[0] as String
            val username = pigeonVar_list[1] as String?
            val password = pigeonVar_list[2] as String?
            return StreamTarget(url, username, password)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            url,
            username,
            password,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as StreamTarget
        return PipelinePigeonUtils.deepEquals(this.url, other.url) &&
            PipelinePigeonUtils.deepEquals(this.username, other.username) &&
            PipelinePigeonUtils.deepEquals(this.password, other.password)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + PipelinePigeonUtils.deepHash(this.url)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.username)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.password)
        return result
    }

    override fun toString(): String = "StreamTarget(url=$url, username=$username, password=$password)"
}

/**
 * Result of `GazerHostApi.prepare`: whether the source/encoder negotiated
 * successfully and, if so, what was actually negotiated.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PrepareResult(
    val ok: Boolean,
    val error: GazerErrorCode? = null,
    val detail: String? = null,
    val negotiatedWidth: Long? = null,
    val negotiatedHeight: Long? = null,
    val negotiatedFps: Long? = null,
    val negotiatedFormat: String? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): PrepareResult {
            val ok = pigeonVar_list[0] as Boolean
            val error = pigeonVar_list[1] as GazerErrorCode?
            val detail = pigeonVar_list[2] as String?
            val negotiatedWidth = pigeonVar_list[3] as Long?
            val negotiatedHeight = pigeonVar_list[4] as Long?
            val negotiatedFps = pigeonVar_list[5] as Long?
            val negotiatedFormat = pigeonVar_list[6] as String?
            return PrepareResult(ok, error, detail, negotiatedWidth, negotiatedHeight, negotiatedFps, negotiatedFormat)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            ok,
            error,
            detail,
            negotiatedWidth,
            negotiatedHeight,
            negotiatedFps,
            negotiatedFormat,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as PrepareResult
        return PipelinePigeonUtils.deepEquals(this.ok, other.ok) &&
            PipelinePigeonUtils.deepEquals(this.error, other.error) &&
            PipelinePigeonUtils.deepEquals(this.detail, other.detail) &&
            PipelinePigeonUtils.deepEquals(this.negotiatedWidth, other.negotiatedWidth) &&
            PipelinePigeonUtils.deepEquals(this.negotiatedHeight, other.negotiatedHeight) &&
            PipelinePigeonUtils.deepEquals(this.negotiatedFps, other.negotiatedFps) &&
            PipelinePigeonUtils.deepEquals(this.negotiatedFormat, other.negotiatedFormat)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + PipelinePigeonUtils.deepHash(this.ok)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.error)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.detail)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.negotiatedWidth)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.negotiatedHeight)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.negotiatedFps)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.negotiatedFormat)
        return result
    }

    override fun toString(): String =
        "PrepareResult(ok=$ok, error=$error, detail=$detail, negotiatedWidth=$negotiatedWidth, " +
            "negotiatedHeight=$negotiatedHeight, negotiatedFps=$negotiatedFps, negotiatedFormat=$negotiatedFormat)"
}

/**
 * One 1Hz statistics sample emitted by the native encoder/publisher.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StatsSample(
    val bitrateKbps: Long,
    val fps: Double,
    val droppedVideoFrames: Long,
    val sentBytes: Long,
    val congestionPercent: Double,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): StatsSample {
            val bitrateKbps = pigeonVar_list[0] as Long
            val fps = pigeonVar_list[1] as Double
            val droppedVideoFrames = pigeonVar_list[2] as Long
            val sentBytes = pigeonVar_list[3] as Long
            val congestionPercent = pigeonVar_list[4] as Double
            return StatsSample(bitrateKbps, fps, droppedVideoFrames, sentBytes, congestionPercent)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            bitrateKbps,
            fps,
            droppedVideoFrames,
            sentBytes,
            congestionPercent,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as StatsSample
        return PipelinePigeonUtils.deepEquals(this.bitrateKbps, other.bitrateKbps) &&
            PipelinePigeonUtils.deepEquals(this.fps, other.fps) &&
            PipelinePigeonUtils.deepEquals(this.droppedVideoFrames, other.droppedVideoFrames) &&
            PipelinePigeonUtils.deepEquals(this.sentBytes, other.sentBytes) &&
            PipelinePigeonUtils.deepEquals(this.congestionPercent, other.congestionPercent)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + PipelinePigeonUtils.deepHash(this.bitrateKbps)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.fps)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.droppedVideoFrames)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.sentBytes)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.congestionPercent)
        return result
    }

    override fun toString(): String =
        "StatsSample(bitrateKbps=$bitrateKbps, fps=$fps, droppedVideoFrames=$droppedVideoFrames, " +
            "sentBytes=$sentBytes, congestionPercent=$congestionPercent)"
}

/**
 * A native pipeline state transition, optionally carrying an error.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StateEvent(
    val state: NativePipelineState,
    val error: GazerErrorCode? = null,
    val detail: String? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): StateEvent {
            val state = pigeonVar_list[0] as NativePipelineState
            val error = pigeonVar_list[1] as GazerErrorCode?
            val detail = pigeonVar_list[2] as String?
            return StateEvent(state, error, detail)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            state,
            error,
            detail,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as StateEvent
        return PipelinePigeonUtils.deepEquals(this.state, other.state) &&
            PipelinePigeonUtils.deepEquals(this.error, other.error) &&
            PipelinePigeonUtils.deepEquals(this.detail, other.detail)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + PipelinePigeonUtils.deepHash(this.state)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.error)
        result = 31 * result + PipelinePigeonUtils.deepHash(this.detail)
        return result
    }

    override fun toString(): String = "StateEvent(state=$state, error=$error, detail=$detail)"
}

private open class PipelinePigeonCodec : StandardMessageCodec() {
    override fun readValueOfType(
        type: Byte,
        buffer: ByteBuffer,
    ): Any? {
        return when (type) {
            129.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    VideoDeviceKind.ofRaw(it.toInt())
                }
            }
            130.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    AudioDeviceKind.ofRaw(it.toInt())
                }
            }
            131.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    NativePipelineState.ofRaw(it.toInt())
                }
            }
            132.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    GazerErrorCode.ofRaw(it.toInt())
                }
            }
            133.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    OutputOrientation.ofRaw(it.toInt())
                }
            }
            134.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    VideoDevice.fromList(it)
                }
            }
            135.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    AudioDevice.fromList(it)
                }
            }
            136.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    StreamConfig.fromList(it)
                }
            }
            137.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    StreamTarget.fromList(it)
                }
            }
            138.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    PrepareResult.fromList(it)
                }
            }
            139.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    StatsSample.fromList(it)
                }
            }
            140.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    StateEvent.fromList(it)
                }
            }
            else -> super.readValueOfType(type, buffer)
        }
    }

    override fun writeValue(
        stream: ByteArrayOutputStream,
        value: Any?,
    ) {
        when (value) {
            is VideoDeviceKind -> {
                stream.write(129)
                writeValue(stream, value.raw.toLong())
            }
            is AudioDeviceKind -> {
                stream.write(130)
                writeValue(stream, value.raw.toLong())
            }
            is NativePipelineState -> {
                stream.write(131)
                writeValue(stream, value.raw.toLong())
            }
            is GazerErrorCode -> {
                stream.write(132)
                writeValue(stream, value.raw.toLong())
            }
            is OutputOrientation -> {
                stream.write(133)
                writeValue(stream, value.raw.toLong())
            }
            is VideoDevice -> {
                stream.write(134)
                writeValue(stream, value.toList())
            }
            is AudioDevice -> {
                stream.write(135)
                writeValue(stream, value.toList())
            }
            is StreamConfig -> {
                stream.write(136)
                writeValue(stream, value.toList())
            }
            is StreamTarget -> {
                stream.write(137)
                writeValue(stream, value.toList())
            }
            is PrepareResult -> {
                stream.write(138)
                writeValue(stream, value.toList())
            }
            is StatsSample -> {
                stream.write(139)
                writeValue(stream, value.toList())
            }
            is StateEvent -> {
                stream.write(140)
                writeValue(stream, value.toList())
            }
            else -> super.writeValue(stream, value)
        }
    }
}

/**
 * Commands Dart issues to the native pipeline (Dart -> Kotlin).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface GazerHostApi {
    /**
     * Enumerates available video sources (back/front camera; UVC devices
     * attached at call time).
     */
    fun listVideoDevices(): List<VideoDevice>

    /** Enumerates available audio sources. */
    fun listAudioDevices(): List<AudioDevice>

    /**
     * Requests OS-level USB permission for [deviceId]. M1 always returns
     * false: no UVC devices are ever listed, so this is never actually
     * invoked with a real device in this milestone.
     */
    suspend fun requestUsbPermission(deviceId: String): Boolean

    /** Negotiates the source/encoder for [config]; must succeed before `start`. */
    suspend fun prepare(config: StreamConfig): PrepareResult

    /** Begins publishing to [target]; only valid after a successful `prepare`. */
    suspend fun start(target: StreamTarget)

    /** Stops publishing and tears down the source/encoder. */
    suspend fun stop()

    /**
     * Adjusts the live video bitrate without a full restart (used by the
     * native `BitrateAdapter` and by Dart-driven manual overrides).
     */
    fun setVideoBitrate(kbps: Long)

    /** Returns the native pipeline's current state synchronously. */
    fun getState(): NativePipelineState

    companion object {
        /** The codec used by GazerHostApi. */
        val codec: MessageCodec<Any?> by lazy {
            PipelinePigeonCodec()
        }

        /** Sets up an instance of `GazerHostApi` to handle messages through the `binaryMessenger`. */
        @JvmOverloads
        fun setUp(
            binaryMessenger: BinaryMessenger,
            api: GazerHostApi?,
            messageChannelSuffix: String = "",
        ) {
            val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.gazer.GazerHostApi.listVideoDevices$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        val wrapped: List<Any?> =
                            try {
                                listOf(api.listVideoDevices())
                            } catch (exception: Throwable) {
                                PipelinePigeonUtils.wrapError(exception)
                            }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.gazer.GazerHostApi.listAudioDevices$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        val wrapped: List<Any?> =
                            try {
                                listOf(api.listAudioDevices())
                            } catch (exception: Throwable) {
                                PipelinePigeonUtils.wrapError(exception)
                            }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.gazer.GazerHostApi.requestUsbPermission$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val deviceIdArg = args[0] as String
                        CoroutineScope(Dispatchers.Main).launch {
                            val wrapped: List<Any?> =
                                try {
                                    listOf(api.requestUsbPermission(deviceIdArg))
                                } catch (exception: Throwable) {
                                    PipelinePigeonUtils.wrapError(exception)
                                }
                            reply.reply(wrapped)
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.gazer.GazerHostApi.prepare$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val configArg = args[0] as StreamConfig
                        CoroutineScope(Dispatchers.Main).launch {
                            val wrapped: List<Any?> =
                                try {
                                    listOf(api.prepare(configArg))
                                } catch (exception: Throwable) {
                                    PipelinePigeonUtils.wrapError(exception)
                                }
                            reply.reply(wrapped)
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.gazer.GazerHostApi.start$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val targetArg = args[0] as StreamTarget
                        CoroutineScope(Dispatchers.Main).launch {
                            val wrapped: List<Any?> =
                                try {
                                    api.start(targetArg)
                                    listOf(null)
                                } catch (exception: Throwable) {
                                    PipelinePigeonUtils.wrapError(exception)
                                }
                            reply.reply(wrapped)
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.gazer.GazerHostApi.stop$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        CoroutineScope(Dispatchers.Main).launch {
                            val wrapped: List<Any?> =
                                try {
                                    api.stop()
                                    listOf(null)
                                } catch (exception: Throwable) {
                                    PipelinePigeonUtils.wrapError(exception)
                                }
                            reply.reply(wrapped)
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.gazer.GazerHostApi.setVideoBitrate$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val kbpsArg = args[0] as Long
                        val wrapped: List<Any?> =
                            try {
                                api.setVideoBitrate(kbpsArg)
                                listOf(null)
                            } catch (exception: Throwable) {
                                PipelinePigeonUtils.wrapError(exception)
                            }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.gazer.GazerHostApi.getState$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        val wrapped: List<Any?> =
                            try {
                                listOf(api.getState())
                            } catch (exception: Throwable) {
                                PipelinePigeonUtils.wrapError(exception)
                            }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
        }
    }
}

/**
 * Events the native pipeline pushes to Dart (Kotlin -> Dart).
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class GazerFlutterApi(
    private val binaryMessenger: BinaryMessenger,
    private val messageChannelSuffix: String = "",
) {
    companion object {
        /** The codec used by GazerFlutterApi. */
        val codec: MessageCodec<Any?> by lazy {
            PipelinePigeonCodec()
        }
    }

    /** Fired on every native state transition. */
    suspend fun onStateChanged(eventArg: StateEvent) {
        val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
        return suspendCancellableCoroutine { continuation ->
            val channelName = "dev.flutter.pigeon.gazer.GazerFlutterApi.onStateChanged$separatedMessageChannelSuffix"
            val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
            channel.send(listOf(eventArg)) {
                if (it is List<*>) {
                    if (it.size > 1) {
                        continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
                    } else {
                        continuation.resume(Unit)
                    }
                } else {
                    continuation.resumeWithException(PipelinePigeonUtils.createConnectionError(channelName))
                }
            }
        }
    }

    /** Fired at 1Hz while prepared/streaming. */
    suspend fun onStats(sampleArg: StatsSample) {
        val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
        return suspendCancellableCoroutine { continuation ->
            val channelName = "dev.flutter.pigeon.gazer.GazerFlutterApi.onStats$separatedMessageChannelSuffix"
            val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
            channel.send(listOf(sampleArg)) {
                if (it is List<*>) {
                    if (it.size > 1) {
                        continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
                    } else {
                        continuation.resume(Unit)
                    }
                } else {
                    continuation.resumeWithException(PipelinePigeonUtils.createConnectionError(channelName))
                }
            }
        }
    }

    /** Fired when a UVC device is physically attached (M1: never fired). */
    suspend fun onUsbAttached(deviceArg: VideoDevice) {
        val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
        return suspendCancellableCoroutine { continuation ->
            val channelName = "dev.flutter.pigeon.gazer.GazerFlutterApi.onUsbAttached$separatedMessageChannelSuffix"
            val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
            channel.send(listOf(deviceArg)) {
                if (it is List<*>) {
                    if (it.size > 1) {
                        continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
                    } else {
                        continuation.resume(Unit)
                    }
                } else {
                    continuation.resumeWithException(PipelinePigeonUtils.createConnectionError(channelName))
                }
            }
        }
    }

    /** Fired when a UVC device is physically detached (M1: never fired). */
    suspend fun onUsbDetached(deviceIdArg: String) {
        val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
        return suspendCancellableCoroutine { continuation ->
            val channelName = "dev.flutter.pigeon.gazer.GazerFlutterApi.onUsbDetached$separatedMessageChannelSuffix"
            val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
            channel.send(listOf(deviceIdArg)) {
                if (it is List<*>) {
                    if (it.size > 1) {
                        continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
                    } else {
                        continuation.resume(Unit)
                    }
                } else {
                    continuation.resumeWithException(PipelinePigeonUtils.createConnectionError(channelName))
                }
            }
        }
    }

    /** Fired after an RTMP auth attempt resolves. */
    suspend fun onAuthResult(okArg: Boolean) {
        val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
        return suspendCancellableCoroutine { continuation ->
            val channelName = "dev.flutter.pigeon.gazer.GazerFlutterApi.onAuthResult$separatedMessageChannelSuffix"
            val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
            channel.send(listOf(okArg)) {
                if (it is List<*>) {
                    if (it.size > 1) {
                        continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
                    } else {
                        continuation.resume(Unit)
                    }
                } else {
                    continuation.resumeWithException(PipelinePigeonUtils.createConnectionError(channelName))
                }
            }
        }
    }
}
