"""Round 2, blocker (2): generalizes Round 1's manual `import bundles.bot_process`.

Round 1 found that `componentize-py`'s dependency-closure discovery only
follows STATIC, module-level `import` edges reachable from the entry app
module -- a bundle's deferred/lazy import (`social_alias_process.py`'s own
`_known_commands()`, by deliberate design, to dodge a circular import) is
invisible to it, producing a runtime `ModuleNotFoundError` unless the
harness statically imports the target module itself.

Round 1 fixed this by hand-adding one `import bundles.bot_process` line --
correct for this one bundle, not a real solution for a bundle host that
must componentize ARBITRARY unchanged bundles without knowing in advance
which of them use deferred imports.

This build-time script (run BEFORE `componentize-py componentize`, on the
host, ordinary CPython -- never inside the sandbox) walks every module
actually present in the `bundles` package directory via
`pkgutil.walk_packages` and generates `waddle_sdk/_bundle_preimports.py`:
one plain, static `import bundles.<name>` line per module found. That
generated file is itself statically imported by `app_entry.py`, so
componentize-py's AST-level discovery sees every one of those edges
regardless of whether the actual bundle code imports them lazily,
dynamically, or not at all in this run.

This generalizes to any bundle: a real bundle host would run the
equivalent of this script over each bundle's OWN shipped directory before
invoking `componentize-py`, rather than hand-picking which lazy imports to
fix.
"""

from __future__ import annotations

import pkgutil
import sys
from pathlib import Path

WADDLE_SDK_ROOT = Path(__file__).resolve().parent.parent / "waddle_sdk"
OUTPUT_PATH = WADDLE_SDK_ROOT / "_bundle_preimports.py"


def discover_bundle_modules() -> list[str]:
    """Return every importable module name under `waddle_sdk/bundles/`."""
    sys.path.insert(0, str(WADDLE_SDK_ROOT))
    import bundles  # the package we're walking

    names = [
        module_info.name
        for module_info in pkgutil.walk_packages(bundles.__path__, prefix="bundles.")
    ]
    return sorted(names)


def main() -> None:
    modules = discover_bundle_modules()
    lines = [
        '"""AUTO-GENERATED by scripts/generate_bundle_preimports.py -- DO NOT EDIT BY HAND.',
        "",
        "Forces componentize-py's static dependency-closure discovery to see every",
        "module physically present under `bundles/`, independent of whether the",
        "bundle code itself imports them lazily, dynamically, or not at all this run.",
        "See that script's docstring and REPORT.md Round 2, blocker (2).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    lines += [f"import {name}  # noqa: F401" for name in modules]
    lines.append("")
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} with {len(modules)} pre-import(s): {modules}")


if __name__ == "__main__":
    main()
