# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import reputation_pb2 as reputation__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reputation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReputationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordEvent = channel.unary_unary(
                '/waddlebot.reputation.ReputationService/RecordEvent',
                request_serializer=reputation__pb2.RecordEventRequest.SerializeToString,
                response_deserializer=reputation__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.GetScore = channel.unary_unary(
                '/waddlebot.reputation.ReputationService/GetScore',
                request_serializer=reputation__pb2.GetScoreRequest.SerializeToString,
                response_deserializer=reputation__pb2.GetScoreResponse.FromString,
                _registered_method=True)


class ReputationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReputationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordEvent,
                    request_deserializer=reputation__pb2.RecordEventRequest.FromString,
                    response_serializer=reputation__pb2.SuccessResponse.SerializeToString,
            ),
            'GetScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScore,
                    request_deserializer=reputation__pb2.GetScoreRequest.FromString,
                    response_serializer=reputation__pb2.GetScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'waddlebot.reputation.ReputationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('waddlebot.reputation.ReputationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReputationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddlebot.reputation.ReputationService/RecordEvent',
            reputation__pb2.RecordEventRequest.SerializeToString,
            reputation__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddlebot.reputation.ReputationService/GetScore',
            reputation__pb2.GetScoreRequest.SerializeToString,
            reputation__pb2.GetScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
