# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import identity_pb2 as identity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LookupIdentity = channel.unary_unary(
                '/waddlebot.identity.IdentityService/LookupIdentity',
                request_serializer=identity__pb2.LookupIdentityRequest.SerializeToString,
                response_deserializer=identity__pb2.LookupIdentityResponse.FromString,
                _registered_method=True)
        self.GetLinkedPlatforms = channel.unary_unary(
                '/waddlebot.identity.IdentityService/GetLinkedPlatforms',
                request_serializer=identity__pb2.GetLinkedPlatformsRequest.SerializeToString,
                response_deserializer=identity__pb2.GetLinkedPlatformsResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LookupIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinkedPlatforms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LookupIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupIdentity,
                    request_deserializer=identity__pb2.LookupIdentityRequest.FromString,
                    response_serializer=identity__pb2.LookupIdentityResponse.SerializeToString,
            ),
            'GetLinkedPlatforms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinkedPlatforms,
                    request_deserializer=identity__pb2.GetLinkedPlatformsRequest.FromString,
                    response_serializer=identity__pb2.GetLinkedPlatformsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'waddlebot.identity.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('waddlebot.identity.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LookupIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddlebot.identity.IdentityService/LookupIdentity',
            identity__pb2.LookupIdentityRequest.SerializeToString,
            identity__pb2.LookupIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinkedPlatforms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/waddlebot.identity.IdentityService/GetLinkedPlatforms',
            identity__pb2.GetLinkedPlatformsRequest.SerializeToString,
            identity__pb2.GetLinkedPlatformsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
