# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentity.proto\x12\x12waddlebot.identity\x1a\x0c\x63ommon.proto\"R\n\x15LookupIdentityRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x18\n\x10platform_user_id\x18\x03 \x01(\t\"\xb8\x01\n\x16LookupIdentityResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bhub_user_id\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\x12>\n\x10linked_platforms\x18\x04 \x03(\x0b\x32$.waddlebot.identity.PlatformIdentity\x12&\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x17.waddlebot.common.Error\"Y\n\x10PlatformIdentity\x12\x10\n\x08platform\x18\x01 \x01(\t\x12\x18\n\x10platform_user_id\x18\x02 \x01(\t\x12\x19\n\x11platform_username\x18\x03 \x01(\t\"?\n\x19GetLinkedPlatformsRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x13\n\x0bhub_user_id\x18\x02 \x01(\x05\"\x8e\x01\n\x1aGetLinkedPlatformsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x37\n\tplatforms\x18\x02 \x03(\x0b\x32$.waddlebot.identity.PlatformIdentity\x12&\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x17.waddlebot.common.Error2\xef\x01\n\x0fIdentityService\x12g\n\x0eLookupIdentity\x12).waddlebot.identity.LookupIdentityRequest\x1a*.waddlebot.identity.LookupIdentityResponse\x12s\n\x12GetLinkedPlatforms\x12-.waddlebot.identity.GetLinkedPlatformsRequest\x1a..waddlebot.identity.GetLinkedPlatformsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPIDENTITYREQUEST']._serialized_start=52
  _globals['_LOOKUPIDENTITYREQUEST']._serialized_end=134
  _globals['_LOOKUPIDENTITYRESPONSE']._serialized_start=137
  _globals['_LOOKUPIDENTITYRESPONSE']._serialized_end=321
  _globals['_PLATFORMIDENTITY']._serialized_start=323
  _globals['_PLATFORMIDENTITY']._serialized_end=412
  _globals['_GETLINKEDPLATFORMSREQUEST']._serialized_start=414
  _globals['_GETLINKEDPLATFORMSREQUEST']._serialized_end=477
  _globals['_GETLINKEDPLATFORMSRESPONSE']._serialized_start=480
  _globals['_GETLINKEDPLATFORMSRESPONSE']._serialized_end=622
  _globals['_IDENTITYSERVICE']._serialized_start=625
  _globals['_IDENTITYSERVICE']._serialized_end=864
# @@protoc_insertion_point(module_scope)
