# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: translate_interaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'translate_interaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btranslate_interaction.proto\x12\x15translate_interaction\"\x80\x01\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0btarget_lang\x18\x02 \x01(\t\x12\x14\n\x0c\x63ommunity_id\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\x12\n\nchannel_id\x18\x05 \x01(\t\x12\r\n\x05token\x18\x06 \x01(\t\"\x85\x02\n\x11TranslateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07skipped\x18\x02 \x01(\x08\x12\x13\n\x0bskip_reason\x18\x03 \x01(\t\x12\x17\n\x0ftranslated_text\x18\x04 \x01(\t\x12\x15\n\roriginal_text\x18\x05 \x01(\t\x12\x15\n\rdetected_lang\x18\x06 \x01(\t\x12\x13\n\x0btarget_lang\x18\x07 \x01(\t\x12\x12\n\nconfidence\x18\x08 \x01(\x02\x12\x10\n\x08provider\x18\t \x01(\t\x12\x0e\n\x06\x63\x61\x63hed\x18\n \x01(\x08\x12\x18\n\x10tokens_preserved\x18\x0b \x01(\x05\x12\r\n\x05\x65rror\x18\x0c \x01(\t\"4\n\x15\x44\x65tectLanguageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"c\n\x16\x44\x65tectLanguageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rdetected_lang\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"$\n\x13\x43leanupCacheRequest\x12\r\n\x05token\x18\x01 \x01(\t\"G\n\x14\x43leanupCacheResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xce\x02\n\x14TranslateInteraction\x12^\n\tTranslate\x12\'.translate_interaction.TranslateRequest\x1a(.translate_interaction.TranslateResponse\x12m\n\x0e\x44\x65tectLanguage\x12,.translate_interaction.DetectLanguageRequest\x1a-.translate_interaction.DetectLanguageResponse\x12g\n\x0c\x43leanupCache\x12*.translate_interaction.CleanupCacheRequest\x1a+.translate_interaction.CleanupCacheResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translate_interaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATEREQUEST']._serialized_start=55
  _globals['_TRANSLATEREQUEST']._serialized_end=183
  _globals['_TRANSLATERESPONSE']._serialized_start=186
  _globals['_TRANSLATERESPONSE']._serialized_end=447
  _globals['_DETECTLANGUAGEREQUEST']._serialized_start=449
  _globals['_DETECTLANGUAGEREQUEST']._serialized_end=501
  _globals['_DETECTLANGUAGERESPONSE']._serialized_start=503
  _globals['_DETECTLANGUAGERESPONSE']._serialized_end=602
  _globals['_CLEANUPCACHEREQUEST']._serialized_start=604
  _globals['_CLEANUPCACHEREQUEST']._serialized_end=640
  _globals['_CLEANUPCACHERESPONSE']._serialized_start=642
  _globals['_CLEANUPCACHERESPONSE']._serialized_end=713
  _globals['_TRANSLATEINTERACTION']._serialized_start=716
  _globals['_TRANSLATEINTERACTION']._serialized_end=1050
# @@protoc_insertion_point(module_scope)
