apiVersion: v1
kind: ConfigMap
metadata:
  name: twitch-collector-config
  namespace: waddlebot
  labels:
    app: twitch-collector
    component: config
data:
  MODULE_NAME: "twitch"
  MODULE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  KUBERNETES_NAMESPACE: "waddlebot"
  KUBERNETES_SERVICE_NAME: "twitch-collector"
  
  # Core API endpoints (will be overridden by environment-specific values)
  CORE_API_URL: "http://core-api:8001"
  CONTEXT_API_URL: "http://core-api:8001/api/context"
  REPUTATION_API_URL: "http://core-api:8001/api/reputation"
  GATEWAY_ACTIVATE_URL: "http://core-api:8001/api/gateway/activate"