apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waddlebot

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: waddlebot
  app.kubernetes.io/component: twitch-collector
  app.kubernetes.io/part-of: waddlebot

images:
- name: waddlebot/twitch-collector
  newTag: latest

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: twitch-collector-config
  envs:
  - config.env

secretGenerator:
- name: twitch-collector-secrets
  envs:
  - secrets.env