apiVersion: v1
kind: Secret
metadata:
  name: twitch-collector-secrets
  namespace: waddlebot
  labels:
    app: twitch-collector
    component: secrets
type: Opaque
stringData:
  # Twitch API credentials (base64 encoded in actual deployment)
  TWITCH_APP_ID: "your_twitch_app_id_here"
  TWITCH_APP_SECRET: "your_twitch_app_secret_here"
  TWITCH_WEBHOOK_SECRET: "your_webhook_secret_here"
  
  # Database connection
  DATABASE_URL: "postgresql://username:password@postgres-service:5432/waddlebot"
  
  # External webhook URL (replace with actual domain)
  TWITCH_WEBHOOK_CALLBACK_URL: "https://your-domain.com/twitch/webhook"
  TWITCH_REDIRECT_URI: "https://your-domain.com/twitch/auth/callback"